[env:expander]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = pico
board_build.core = earlephilhower
board_build.f_cpu = 250000000L
board_build.filesystem_size = 0
board_build.flash_size = 8M
board_build.boot2 = boot2_w25q080_2_padded_checksum
upload_protocol = picotool
monitor_speed = 115200
build_flags =
    -O3
    -std=gnu++17
